package entity;
// Generated 30 janv. 2016 21:44:13 by Hibernate Tools 3.6.0

import helper.Bootstrap;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 * HisLogin generated by hbm2java
 */
@Entity
@Table(name = "his_login", uniqueConstraints = {
    })
@AttributeOverrides({
    @AttributeOverride(name = "id", column = @Column(name = "id"))
    ,
    @AttributeOverride(name = "create_uid", column = @Column(name = "create_uid"))
    ,
    @AttributeOverride(name = "update_uid", column = @Column(name = "update_uid"))
    ,
    @AttributeOverride(name = "create_time", column = @Column(name = "create_time"))
    ,
    @AttributeOverride(name = "update_time", column = @Column(name = "update_time"))
})
public class HisLogin extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "his_login_id_seq")
    @SequenceGenerator(name = "his_login_id_seq", sequenceName = "his_login_id_seq", allocationSize = 1)    
    private Integer id;
    
    
    @Column(name = "message")
    private String message;

    public HisLogin() {
    }

    public HisLogin(int createId, int writeId, String message) {
        this.message = message;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }   

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public void create(Session session, String message, int user_id) {

        try {
            session.beginTransaction();
            HisLogin hislogin = new HisLogin(user_id, user_id, message);
            id = (Integer) session.save(hislogin);

            //Save the employee in database
            session.save(hislogin);
            //Commit the transaction
            session.getTransaction().commit();
        } catch (HibernateException e) {
            e.printStackTrace();
        } finally {
            session.close();
        }
        System.out.println("Rows inserted in table affected: " + id);
    }

}
